from dataclasses import dataclass
from typing import Literal, Protocol, Self

from prometheus_client import REGISTRY, CollectorRegistry, Counter, Histogram

METRICS_NAMESPACE = "energy_trading_pypeline"
PRODUCER_METRICS_SUBSYSTEM = "consumer"

ConsumerProcessingOutcome = Literal[
    "valid",
    "duplicate",
    "stale",
    "invalid",
]


class ConsumerMetrics(Protocol):
    def record_message_processed(
        self,
        *,
        outcome: ConsumerProcessingOutcome,
        duration_seconds: float,
    ) -> None:
        """Record a successfully managed consumer message."""

    def record_invalid_event_persisted(self) -> None:
        """Record a successfully persisted invalid event."""

    def record_alerts_generated(self, *, count: int) -> None:
        """Record generated market alerts."""


@dataclass(frozen=True)
class NoOpConsumerMetrics:
    def record_message_processed(
        self,
        *,
        outcome: ConsumerProcessingOutcome,
        duration_seconds: float,
    ) -> None:
        return None

    def record_invalid_event_persisted(self) -> None:
        return None

    def record_alerts_generated(self, *, count: int) -> None:
        return None


@dataclass(frozen=True)
class PrometheusConsumerMetrics:
    _processed_messages: Counter
    _processing_duration: Histogram
    _invalid_events_persisted: Counter
    _alerts_generated: Counter

    @classmethod
    def create(cls, *, registry: CollectorRegistry | None = None) -> Self:
        target_regsitry = REGISTRY if registry is None else registry
        return cls(
            _processed_messages=Counter(
                name="processed_messages",
                documentation=(
                    "Total number of Kafka messages successfully handled by the consumer, "
                    "grouped by processing outcome."
                ),
                labelnames=("outcome",),
                namespace=METRICS_NAMESPACE,
                subsystem=PRODUCER_METRICS_SUBSYSTEM,
                registry=target_regsitry,
            ),
            _processing_duration=Histogram(
                name="processing_duration_seconds",
                documentation=(
                    "Duration of consumer message processing in seconds, "
                    "grouped by processing outcome."
                ),
                labelnames=("outcome",),
                namespace=METRICS_NAMESPACE,
                subsystem=PRODUCER_METRICS_SUBSYSTEM,
                registry=registry,
                buckets=(
                    0.001,
                    0.005,
                    0.01,
                    0.025,
                    0.05,
                    0.1,
                    0.25,
                    0.5,
                    1.0,
                    2.5,
                    5.0,
                    10.0,
                ),
            ),
            _invalid_events_persisted=Counter(
                name="invalid_events_persisted",
                documentation=(
                    "Total number of invalid Kafka messages successfully persisted by the consumer."
                ),
                namespace=METRICS_NAMESPACE,
                subsystem=PRODUCER_METRICS_SUBSYSTEM,
                registry=registry,
            ),
            _alerts_generated=Counter(
                name="alerts_generated",
                documentation=("Total number of market alerts generated by the consumer.."),
                namespace=METRICS_NAMESPACE,
                subsystem=PRODUCER_METRICS_SUBSYSTEM,
                registry=registry,
            ),
        )

    def record_message_processed(
        self,
        *,
        outcome: ConsumerProcessingOutcome,
        duration_seconds: float,
    ) -> None:
        self._processed_messages.labels(outcome=outcome).inc()
        self._processing_duration.labels(outcome=outcome).observe(duration_seconds)

    def record_invalid_event_persisted(self) -> None:
        self._invalid_events_persisted.inc()

    def record_alerts_generated(self, *, count: int) -> None:
        if count <= 0:
            return

        self._alerts_generated.inc(count)


def create_consumer_metrics(*, enabled: bool) -> ConsumerMetrics | NoOpConsumerMetrics:
    if not enabled:
        return NoOpConsumerMetrics()

    return PrometheusConsumerMetrics.create()
